apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-meilisearch
  namespace: devana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devana-meilisearch
  template:
    metadata:
      labels:
        app: devana-meilisearch
    spec:
      containers:
        - name: devana-meilisearch
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          image: getmeili/meilisearch:v1.9
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_NO_ANALYTICS # Disable telemetry
              value: "true"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meilisearch-volume
              mountPath: /meili_data
      volumes:
        - name: meilisearch-volume
          persistentVolumeClaim:
            claimName: meilisearch
      imagePullSecrets:
        - name: registry-secret-scriptor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch
  namespace: devana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: devana-meilisearch-service
  namespace: devana
spec:
  selector:
    app: devana-meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
